title: iptv直播源播放列表
description: GitHub自动程序生成的最新可用的iptv直播源播放列表
show_downloads: true
google_analytics:
remote_theme: pages-themes/cayman@v0.2.0

collections:
  pages:
    output: true
    permalink: /:path/
