title: 每天更新|最新iptv直播源播放列表|Github开源
description: 每天更新最新可用的iptv直播源播放列表|Github开源
show_downloads: false
url: https://live.zbds.top
google_analytics: # 如果有 Google Analytics 代码，请添加到这里
theme: jekyll-theme-cayman
#remote_theme: pages-themes/cayman@v0.2.0
encoding: "utf-8"

# 添加 Google AdSense 配置
google_adsense: ca-pub-6941806026814791

collections:
  pages:
    output: true
    permalink: /:path/

# 修改网站图标配置，使用现有的图标
favicon: favicon.ico
apple_touch_icon: favicon.ico

# 添加社交媒体图标
social:
  github: vbskycn/iptv
  telegram: starkluistn98

# 添加自定义样式
sass:
  style: compressed

