name: Deploy Jekyll with GitHub Pages dependencies

on:
  # 当推送到默认分支时触发
  push:
    branches: ["master"]

  # 允许从 Actions 标签页手动触发
  workflow_dispatch:

  # 每天 UTC 时间 2 点自动触发
  schedule:
    - cron: '0 2 * * *'

# 设置 GITHUB_TOKEN 的权限，允许读取仓库内容并写入到 GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# 允许只有一个并发部署，不会取消正在进行中的部署
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # 构建作业
  build:
    runs-on: ubuntu-latest
    steps:
      # 获取仓库代码
      - name: 检出代码
        uses: actions/checkout@v3

      # 配置 GitHub Pages
      - name: 设置 Pages
        uses: actions/configure-pages@v3

      # 使用 Jekyll 构建网站
      - name: 使用 Jekyll 构建
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      # 上传构建好的网站到 artifacts
      - name: 上传 artifact
        uses: actions/upload-pages-artifact@v2

  # 部署作业
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      # 部署到 GitHub Pages
      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
