name: sync_live_list

on:
  # 每小时的第5分钟触发
  schedule:
    - cron: '5 * * * *'
  # 允许手动运行工作流
  workflow_dispatch:

jobs:
  sync_live_list:
    # 在最新的 Ubuntu 操作系统上运行
    runs-on: ubuntu-latest

    # 设置环境变量
    env:
      MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

    outputs:
      changes_detected: ${{ steps.detect_changes.outputs.changes_detected }}

    steps:
      # 第一步：检出仓库代码
      - name: Checkout repository
        uses: actions/checkout@v2

      # 第二步：设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # 第三步：安装依赖
      - name: Install dependencies
        run: |
          pip install requests

      # 第四步：列出 tv 目录中的文件，调试路径问题
      - name: List files in tv directory
        run: |
          ls -la tv

      # 第五步：运行 syn_live_list.py 脚本
      - name: Run syn_live_list.py
        run: |
          cd tv
          python syn_live_list.py

      # 第六步：列出运行脚本后生成的文件，确认文件生成情况
      - name: List generated files
        run: |
          ls -la tv

      # 第七步：检查是否有更改
      - name: Check for changes
        run: |
          git diff --exit-code || echo "changes detected"
        id: detect_changes

      # 第八步：提交并推送更改（仅当有更改时）
      - name: Commit and push changes
        if: steps.detect_changes.outputs.changes_detected == 'changes detected'
        run: |
          cd tv
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Sync live list"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
