name: sync_live_list

on:
  schedule:
    - cron: '5 * * * *'
  workflow_dispatch:

jobs:
  sync_live_list:
    runs-on: ubuntu-latest

    env:
      MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests

    - name: List files in tools directory
      run: |
        ls -la tools

    # 运行 syn_live_list.sh.py 脚本
    - name: Run syn_live_list.py
      run: |
        python tools/syn_live_list.py

    - name: Copy files to /tv directory
      run: |
        for file in tools/*.txt tools/*.m3u; do
          if [ ! -e "tv/$(basename $file)" ]; then
            cp $file tv/
          fi
        done

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        cd tv
        if [ -n "$(git status --porcelain)" ]; then
          git add .
          git commit -m "Sync live list"
          git push
        else
          echo "No changes to commit"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
